#ifndef BIOTRACKERPLUGIN_GLOBAL_H
#define BIOTRACKERPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BIOTRACKERPLUGIN_LIBRARY)
#  define BIOTRACKERPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define BIOTRACKERPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BIOTRACKERPLUGIN_GLOBAL_H
