#!/bin/bash

echo "running pre commit hook to check style guide!" >&2
OPTIONS="--options=astyle/.astylerc"

RETURN=0
ASTYLE=$(which astyle)
if [ $? -ne 0 ]; then
    echo "[!] astyle not installed. Unable to check source file format policy." >&2
    exit 1
fi

FILES=`git diff --cached --name-only --diff-filter=ACMR | grep -E "\.(cpp|h)$"`
for FILE in $FILES; do
    $ASTYLE $OPTIONS < $FILE > /tmp/diff
    if [ $? -ne 0 ]; then
        echo "[!] $FILE does not respect the agreed coding style." >&2
        change=$(diff /tmp/diff $FILE)
        echo "diff is: " >&2
        RETURN=1
    fi
done

if [ $RETURN -eq 1 ]; then
    echo "" >&2
    echo "Make sure you have run astyle for all files with the following options:" >&2
    echo $OPTIONS >&2
fi

exit $RETURN
