#!/bin/bash

function astyle {
    for FILE in $FILES_TO_ADJUST; do
        $ASTYLE $OPTIONS $FILE
        git add $FILE
    done
}

echo "running pre commit hook to check style guide!" >&2
OPTIONS="--options=astyle/.astylerc"

RETURN=0
ASTYLE=$(which astyle)
if [ $? -ne 0 ]; then
    echo "[!] astyle not installed. Unable to check source file format policy." >&2
    echo "If you wan't to bypass the check you can run 'git commit --no-verify'" >&2
    exit 1
fi

FILES=`git diff --cached --name-only --diff-filter=ACMR | grep -E "\.(cpp|h)$"`
FILES_TO_ADJUST=()
for FILE in $FILES; do
    $ASTYLE $OPTIONS < $FILE > /tmp/diff
    DIFF=$(diff -B $FILE /tmp/diff)

    if [ "$DIFF" != "" ]; then
        FILES_TO_ADJUST+="$FILE "
        echo "[!] $FILE does not respect the agreed coding style." >&2
        echo "diff is: " >&2
        echo "$DIFF" >&2
        RETURN=1
    fi
    rm /tmp/diff
done

if [ $RETURN -eq 1 ]; then
    
    # Allows us to read user input below, assigns stdin to keyboard
    exec < /dev/tty
    read -r -p "Do you wan't to run the automatic style adjustment? [Y/n]" yn

    if [ "$yn" = "" ]; then
        yn='Y'
    fi
    case $yn in
        [Yy] ) 
            echo "adjusting files: $FILES_TO_ADJUST"
            astyle
            RETURN=0
            ;;
        [Nn] ) 
            echo "Make sure you have run:" >&2
            echo "$ASTYLE $OPTIONS --recursive "biotracker/*.cpp"" >&2
            echo "$ASTYLE $OPTIONS --recursive "biotracker/*.h"" >&2
            ;;
        * ) 
            echo "Please answer y or n for yes or no."
            ;;
    esac 
fi

exit $RETURN
