#ifndef BIOTRACKERTRACKINGPLUGIN_GLOBAL_H
#define BIOTRACKERTRACKINGPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BIOTRACKERTRACKINGPLUGIN_LIBRARY)
#  define BIOTRACKERTRACKINGPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define BIOTRACKERTRACKINGPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BIOTRACKERTRACKINGPLUGIN_GLOBAL_H
